parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Ferror\Payments\Presentation\Console\:
        resource: '../src/Payments/Presentation/Console/'

    Ferror\Payments\Presentation\Web\:
        resource: '../src/Payments/Presentation/Web/'
        tags: ['controller.service_arguments']

    Ferror\Payments\Application\Action\:
        resource: '../src/Payments/Application/Action/'

# MEMORY
    Ferror\Payments\Infrastructure\Memory\Repository\MemoryCustomerRepository: ~
    Ferror\Payments\Infrastructure\Memory\Query\MemoryCustomerQuery: ~

    Ferror\Payments\Application\Repository\CustomerRepository: '@Ferror\Payments\Infrastructure\Memory\Repository\MemoryCustomerRepository'
    Ferror\Payments\Application\Query\CustomerQuery: '@Ferror\Payments\Infrastructure\Memory\Query\MemoryCustomerQuery'
